"""create_use_cases

Revision ID: f600a112a7bd
Revises:
Create Date: 2026-06-22 14:44:38.284170
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "f600a112a7bd"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "use_cases",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("tier", sa.String(length=20), nullable=False),
        sa.Column("visibility", sa.String(length=30), nullable=False),
        sa.Column("log_format", sa.String(length=50), nullable=False),
        sa.Column("template", sa.Text(), nullable=False),
        sa.Column("template_encrypted", sa.LargeBinary(), nullable=True),
        sa.Column("olf_version", sa.String(length=20), nullable=False),
        sa.Column("mitre_tactics", sa.JSON(), nullable=False),
        sa.Column("mitre_techniques", sa.JSON(), nullable=False),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column("target_ids", sa.JSON(), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("use_cases")
    # ### end Alembic commands ###
